/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_mysql;

/**
 *
 * @author theprathyaksh
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;//Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.ResultSetMetaData;
//import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Java_MySQL extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "b182782";
    private static final String dataConn = "jdbc:mysql://localhost:3306/connector";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i,id,deleteItem;
    
    
    
    public Java_MySQL() {
        initComponents();
    }
    public void upDateDB()
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("select *from connector");
        
        rs = pst.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        
        q = stData.getColumnCount();
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        RecordTable.setRowCount(0);
        
        while(rs.next()){
            Vector columnData = new Vector();
            for(i=1;i<=q;i++)
            {
                //columnData.add(rs.getString("id"));
                columnData.add(rs.getInt("ID"));
                columnData.add(rs.getString("FirstName"));
                columnData.add(rs.getString("LastName"));
                columnData.add(rs.getString("Address"));
                columnData.add(rs.getInt("PinCode"));
                columnData.add(rs.getInt("Phone"));
            }
             RecordTable.addRow(columnData);
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jxtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jtxtPinCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jbtnupdate = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        JbtnDelete = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel2.setText("Student ID:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jtxtID.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jPanel6.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 370, 30));

        jLabel3.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel3.setText("FirstName:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jtxtFirstName.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jtxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstNameActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 51, 370, 30));

        jxtAddress.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxtAddressActionPerformed(evt);
            }
        });
        jPanel6.add(jxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 370, 30));

        jLabel4.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel4.setText("Address:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel5.setText("LastName:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jtxtLastName.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jPanel6.add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 370, 30));

        jLabel6.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel6.setText("Pin Code:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jtxtPhone.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jtxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPhoneActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 370, 30));

        jtxtPinCode.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jPanel6.add(jtxtPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 370, 30));

        jLabel7.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel7.setText("Phone:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "LastName", "Address", "Pin Code", "Phone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 510, 260));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 550, 560));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Gotham", 1, 36)); // NOI18N
        jLabel1.setText("MySQL Connection");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 890, 100));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jbtnupdate.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jbtnupdate.setText("Update Data");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 60));

        jbtnAddNew.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jbtnAddNew.setText("Add New Data");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 60));

        jbtnReset.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 60));

        jbtnPrint.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 60));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 480));

        jButton5.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jButton5.setText("jButton1");
        jPanel15.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 60));

        jButton6.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jButton6.setText("jButton1");
        jPanel15.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 60));

        jButton7.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jButton7.setText("jButton1");
        jPanel15.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 60));

        jButton8.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jButton8.setText("jButton1");
        jPanel15.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 60));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 330, 560));

        JbtnDelete.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        JbtnDelete.setText("Delete");
        JbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDeleteActionPerformed(evt);
            }
        });
        jPanel11.add(JbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 60));

        jbtnExit.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 280, 60));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 330, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 930, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstNameActionPerformed

    private void jxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxtAddressActionPerformed

    private void jtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPhoneActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtID.setText("");
        jtxtFirstName.setText("");
        jtxtLastName.setText("");
        jxtAddress.setText("");
        jtxtPinCode.setText("");
        jtxtPhone.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Cofirm if you want to exit","MYSQL Connector",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed

        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("insert into connector(ID,Firstname,LastName,Address,PinCode,Phone)value(?,?,?,?,?,?)");
        
        pst.setString(1,jtxtID.getText());
        pst.setString(2,jtxtFirstName.getText());
        pst.setString(3,jtxtLastName.getText());
        pst.setString(4,jxtAddress.getText());
        //pst.setString(5,jtxtPinCode.getText());
        pst.setInt(5, Integer.parseInt(jtxtPinCode.getText()));
        pst.setInt(6, Integer.parseInt(jtxtPhone.getText()));
        //pst.setString(6,jtxtPhone.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this,"Record Added");
        upDateDB();
         }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        }
          catch (SQLException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        } 
         
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("update connector set ID=?, FirstName=?,LastName=?,Address=?,PinCode=?,Phone=? where ID=?");
        
        pst.setString(1,jtxtID.getText());
        pst.setString(2,jtxtFirstName.getText());
        pst.setString(3,jtxtLastName.getText());
        pst.setString(4,jxtAddress.getText());
        pst.setInt(5, Integer.parseInt(jtxtPinCode.getText()));
        pst.setInt(6, Integer.parseInt(jtxtPhone.getText()));
        pst.setString(7,jtxtID.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this,"Record Updated");
        upDateDB();
         }
         catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        }
          catch (SQLException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        jtxtID.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        jtxtFirstName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtLastName.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jxtAddress.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtPinCode.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        jtxtPhone.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in Progress");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer Found",e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void JbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null,"confirm if you want to delete item",
                    "Warning",JOptionPane.YES_NO_OPTION);
            
            if(deleteItem == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from connector where id=?");
                pst.setInt(1,id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Recorded updated");
                upDateDB();
                
                jtxtID.setText("");
                jtxtFirstName.setText("");
                jtxtLastName.setText("");
                jxtAddress.setText("");
                jtxtPinCode.setText("");
                jtxtPhone.setText("");
                
                
            }
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        }
          catch (SQLException ex) {
            Logger.getLogger(Java_MySQL.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_JbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Java_MySQL().setVisible(true);
                Java_MySQL temp=new Java_MySQL();
                temp.upDateDB();
                temp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnDelete;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtPinCode;
    private javax.swing.JTextField jxtAddress;
    // End of variables declaration//GEN-END:variables
}
